### ISSUE TITLE
Bug: Validation of email

### ISSUE THREAD

**Issue by teger** [OneUptime/oneuptime#736]
Hi, 

I create a user at first startup of application.
I logged on application and all is Ok.

if i log in from an other browser, the application, i have an error and it shows : 
Email is not verified. We have sent you an email with the verification link. Please do not forget to check spam.

I don't received the email and i don't find in the interface how to relauch this validation email.

Thanks for your help,

<img width="733" alt="Capture d’écran 2023-08-24 à 16 10 14" src="https://github.com/OneUptime/oneuptime/assets/1482395/6907defe-6fc0-4f16-9c81-f3885b39a25a">

**Comment by simlarsen** [comment]
Please update your instance to latest. This has been fixed in past releases.

**Comment by teger** [comment]
I use the lastest version on release branch

I pull just now
~/oneuptime$ git pull
From https://github.com/OneUptime/oneuptime
   a87435966e..ebd7ae876b  release          -> origin/release
 * [new tag]               7.0.647          -> 7.0.647
 * [new tag]               build-number-647 -> build-number-647
Updating a87435966e..ebd7ae876b
Fast-forward
 Common/Types/Workflow/Component.ts                                   |  1 +
 Common/Types/Workflow/Components/Slack.ts                            |  7 ++++---
 CommonServer/Services/UserCallService.ts                             |  6 +++++-
 CommonServer/Services/UserSmsService.ts                              |  6 +++++-
 CommonServer/Types/Workflow/Components/Slack/SendMessageToChannel.ts | 11 ++++++++++-
 CommonUI/src/Components/Workflow/Utils.ts                            |  6 ++++++
 6 files changed, 31 insertions(+), 6 deletions(-)


And my branch is release.

And i have always the same problem on the connection with a message error : 

Email is not verified. We have sent you an email with the verification link. Please do not forget to check spam.


Thanks for your help

**Comment by teger** [comment]
Question : after pull the new version, i run

export $(grep -v '^#' config.env | xargs) && docker compose up --remove-orphans -d

I don't have npm installed on my server.

It it the good command ? Or i use a docker compose build before maybe ?

Thaks for your help,

**Comment by teger** [comment]
Hi,

i am still face this issue, after re-pull and retstart the docker images.

My account is not validated again !!
<img width="739" alt="Capture d’écran 2023-08-24 à 22 55 47" src="https://github.com/OneUptime/oneuptime/assets/1482395/6fc689c8-a54e-4997-9575-5adda290a713">

Thank you for your help,
